title: mayurg.in
description: MBBS Notes & Medical Resources

url: ""
baseurl: ""

markdown: kramdown

permalink: pretty

collections:
  notes:
    output: true
    permalink: /notes/:name/

plugins: []

exclude:
  - README.md