title: mayurg.in

tagline: Medical Resources for MBBS Students

description: Notes, Previous Year Question Papers, Practical Resources and Study Material for MBBS Students.

author:
  name: Mayur Gangadhar
  college: East Point College of Medical Sciences & Research Centre
  university: RGUHS

copyright: "© 2026 mayurg.in"

email: gmail@mayurg.in

social:
  github: https://github.com/mayurgangadhar